//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shetalent_Events
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShetalentEventData_1Entities : DbContext
    {
        public ShetalentEventData_1Entities()
            : base("name=ShetalentEventData_1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GridView_Result> GridView()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GridView_Result>("GridView");
        }
    }
}
